export type UserRole = 'SOLICITANTE' | 'AGENTE';
export type TicketStatus = 'esperando_agente' | 'abierto' | 'pendiente' | 'programado' | 'en_progreso' | 'resuelto' | 'cerrado';
export type TicketPriority = 'baja' | 'media' | 'alta' | 'crítica';

export interface Profile {
  id: string;
  full_name: string | null;
  role: UserRole;
  created_at: string;
  updated_at: string;
}

export interface Restaurante {
  id: string;
  sigla: string;
  centro_costo: string | null;
  store_id: string | null;
  compania: string | null;
  nombre_restaurante: string;
  direccion: string | null;
  region: string | null;
  razon_social: string | null;
}

export interface CatalogoServicio {
  id: string; // UUID
  categoria: string;
  subcategoria: string;
  elemento: string;
  activo: boolean;
}

export interface Zona {
  id: string; // UUID
  nombre: string;
  activo: boolean;
}

export interface TicketInsert {
  id?: string;
  numero_ticket?: number;
  titulo: string;
  descripcion: string;
  prioridad?: TicketPriority;
  estado?: TicketStatus;
  creado_por: string; // References profiles
  adjuntos?: string[]; // URLs from bucket
  vencimiento_sla?: string; // Timestamp for SLA
  agente_asignado_id?: string | null; // References profiles
  restaurante_id: string; // References restaurantes
  catalogo_servicio_id: string; // References catalogo_servicios
  zona_id: string; // References zonas
  fecha_programada?: string | null; // Timestamp for scheduled visit
}

export interface Ticket extends TicketInsert {
  id: string;
  numero_ticket: number;
  fecha_creacion: string;
  actualizado_en: string;
  estado: TicketStatus;
  prioridad: TicketPriority;
  profiles?: {
    full_name: string | null;
  };
  agente?: {
    full_name: string | null;
  };
  restaurantes?: Restaurante | null; // Fixed from 'restaurante' to 'restaurantes' for JOIN compatibility
  ticket_messages?: TicketMessage[];
  respuesta_agente?: string | null;
  fecha_resolucion?: string | null;
  calificacion?: number;
  feedback_cliente?: string | null;
  catalogo_servicios?: CatalogoServicio | null;
  zona?: Zona | null;
}

export interface TicketMessageInsert {
  id?: string;
  ticket_id: string;
  sender_id: string; // References profiles
  mensaje: string;
  adjuntos?: string[]; // URLs from bucket
  es_sistema?: boolean;
  tipo_evento?: string; // e.g. 'texto', 'visita_programada'
}

export interface TicketMessage extends TicketMessageInsert {
  id: string;
  creado_en: string;
  tipo_evento: string; // e.g. 'texto', 'visita_programada'
  sender_profile?: {
    full_name: string | null;
    role: UserRole;
  };
}

export interface Notification {
  id: string;
  user_id: string;
  ticket_id: string;
  mensaje: string;
  leida: boolean;
  creado_en: string;
}

// In a real application with a complex database schema generated by Supabase,
// this file would contain the `Database` type output from `supabase gen types typescript`.
// For our current implementation, we just need basic role typing.
